import React from 'react';
import { AnalysisResult } from '../types';
import { ShieldCheck, ShieldAlert, AlertTriangle, FileText, Activity, Zap, Eye, Layers, ScanFace, Download } from 'lucide-react';
import { Radar, RadarChart, PolarGrid, PolarAngleAxis, ResponsiveContainer } from 'recharts';

interface ResultsDashboardProps {
  result: AnalysisResult;
  onReset: () => void;
  caseId: string;
}

const ResultsDashboard: React.FC<ResultsDashboardProps> = ({ result, onReset, caseId }) => {
  const isReal = result.verdict === 'REAL';
  const isFake = result.verdict === 'FAKE';
  const colorClass = isReal ? 'text-accent-400' : isFake ? 'text-danger-400' : 'text-yellow-400';
  const bgClass = isReal ? 'bg-accent-500' : isFake ? 'bg-danger-500' : 'bg-yellow-500';

  const chartData = [
    { subject: 'Light', A: result.technicalMetrics.lightingConsistency, fullMark: 10 },
    { subject: 'Texture', A: result.technicalMetrics.textureNaturalness, fullMark: 10 },
    { subject: 'Anatomy', A: result.technicalMetrics.anatomyCorrectness, fullMark: 10 },
    { subject: 'Context', A: result.technicalMetrics.backgroundCoherence, fullMark: 10 },
  ];

  // Circular progress calculation
  const radius = 60;
  const circumference = 2 * Math.PI * radius;
  const strokeDashoffset = circumference - (result.score / 100) * circumference;

  const handleDownloadReport = () => {
    const date = new Date().toLocaleString();
    const reportContent = `
================================================================
              TRUESIGHT AI // FORENSIC ANALYSIS REPORT
================================================================
CASE ID      : ${caseId}
DATE         : ${date}
VERDICT      : ${result.verdict}
TRUST SCORE  : ${result.score}/100
================================================================

[ EXECUTIVE SUMMARY ]
${result.summary}

[ DETECTED ARTIFACTS ]
${result.artifacts.map(a => `- ${a}`).join('\n')}

[ TECHNICAL METRICS ]
- Lighting Consistency : ${result.technicalMetrics.lightingConsistency}/10
- Texture Naturalness  : ${result.technicalMetrics.textureNaturalness}/10
- Anatomy Correctness  : ${result.technicalMetrics.anatomyCorrectness}/10
- Background Coherence : ${result.technicalMetrics.backgroundCoherence}/10

[ REASONING ]
${result.reasoning}

================================================================
Generated by TrueSight AI Media Integrity System
Powered by Gemini 3.0 Pro Vision
================================================================
`;

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `TrueSight-Case-${caseId}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="w-full max-w-5xl mx-auto space-y-8 animate-fade-in pb-12">
      
      {/* Header Verdict Section */}
      <div className="flex justify-between items-end pb-2 border-b border-white/10">
          <div>
            <div className="text-xs font-mono text-gray-500 mb-1">CASE ID: {caseId}</div>
            <h1 className="text-3xl font-bold text-white">Analysis Results</h1>
          </div>
          <button 
            onClick={handleDownloadReport}
            className="flex items-center gap-2 px-4 py-2 bg-white/5 hover:bg-white/10 border border-white/10 rounded-lg text-sm text-gray-300 transition-colors"
          >
            <Download size={16} />
            Export Case File
          </button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        
        {/* Score Card */}
        <div className="glass-panel p-8 rounded-2xl flex flex-col items-center justify-center relative overflow-hidden group">
            <div className={`absolute inset-0 opacity-5 ${bgClass}`}></div>
            
            {/* Circular Gauge */}
            <div className="relative w-40 h-40 mb-4">
                <svg className="w-full h-full -rotate-90" viewBox="0 0 140 140">
                    <circle cx="70" cy="70" r={radius} fill="none" stroke="#1f2937" strokeWidth="10" />
                    <circle 
                        cx="70" cy="70" r={radius} fill="none" 
                        stroke="currentColor" strokeWidth="10" strokeLinecap="round"
                        strokeDasharray={circumference} strokeDashoffset={strokeDashoffset}
                        className={`${colorClass} transition-all duration-1000 ease-out`}
                    />
                </svg>
                <div className="absolute inset-0 flex flex-col items-center justify-center">
                    <span className={`text-4xl font-bold font-mono ${colorClass}`}>{result.score}</span>
                    <span className="text-xs text-gray-500 font-mono uppercase mt-1">Trust Score</span>
                </div>
            </div>

            <h2 className={`text-2xl font-bold tracking-widest uppercase ${colorClass}`}>
                {result.verdict}
            </h2>
        </div>

        {/* Summary Card */}
        <div className="md:col-span-2 glass-panel p-8 rounded-2xl flex flex-col justify-between">
             <div className="flex items-center gap-3 mb-4">
                <div className={`p-2 rounded-lg ${isReal ? 'bg-accent-500/10' : isFake ? 'bg-danger-500/10' : 'bg-yellow-500/10'}`}>
                    {isReal && <ShieldCheck className={`w-6 h-6 ${colorClass}`} />}
                    {isFake && <ShieldAlert className={`w-6 h-6 ${colorClass}`} />}
                    {!isReal && !isFake && <AlertTriangle className={`w-6 h-6 ${colorClass}`} />}
                </div>
                <h3 className="text-lg font-semibold text-white">Forensic Summary</h3>
             </div>
             <p className="text-gray-300 leading-relaxed text-lg border-l-2 border-white/10 pl-4">
                "{result.summary}"
             </p>
        </div>
      </div>

      {/* Technical Deep Dive */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          
          {/* Radar Chart */}
          <div className="glass-panel p-6 rounded-2xl">
            <h4 className="text-sm font-mono text-gray-500 uppercase mb-6 flex items-center gap-2">
                <Activity size={16} /> Metric Analysis
            </h4>
            <div className="h-[300px] w-full">
                <ResponsiveContainer width="100%" height="100%">
                <RadarChart cx="50%" cy="50%" outerRadius="70%" data={chartData}>
                    <PolarGrid stroke="#334155" />
                    <PolarAngleAxis dataKey="subject" tick={{ fill: '#94a3b8', fontSize: 12, fontWeight: 500 }} />
                    <Radar
                    name="Metrics"
                    dataKey="A"
                    stroke={isReal ? '#10b981' : isFake ? '#ef4444' : '#eab308'}
                    fill={isReal ? '#10b981' : isFake ? '#ef4444' : '#eab308'}
                    fillOpacity={0.4}
                    />
                </RadarChart>
                </ResponsiveContainer>
            </div>
             <div className="grid grid-cols-2 gap-4 mt-2">
                 <MetricRow label="Lighting" value={result.technicalMetrics.lightingConsistency} icon={<Zap size={14}/>} />
                 <MetricRow label="Texture" value={result.technicalMetrics.textureNaturalness} icon={<ScanFace size={14}/>} />
                 <MetricRow label="Anatomy" value={result.technicalMetrics.anatomyCorrectness} icon={<Eye size={14}/>} />
                 <MetricRow label="Background" value={result.technicalMetrics.backgroundCoherence} icon={<Layers size={14}/>} />
             </div>
          </div>

          {/* Evidence List */}
          <div className="glass-panel p-6 rounded-2xl flex flex-col">
            <h4 className="text-sm font-mono text-gray-500 uppercase mb-6 flex items-center gap-2">
                <FileText size={16} /> Detected Artifacts
            </h4>
            
            <div className="flex-1 overflow-y-auto pr-2 custom-scrollbar space-y-3">
                {result.artifacts.length > 0 ? (
                    result.artifacts.map((artifact, idx) => (
                        <div key={idx} className="bg-black/20 p-3 rounded-lg border border-white/5 flex gap-3 group hover:border-white/10 transition-colors">
                            <span className="text-danger-500 font-mono text-sm mt-0.5">0{idx + 1}</span>
                            <span className="text-gray-300 text-sm">{artifact}</span>
                        </div>
                    ))
                ) : (
                    <div className="flex flex-col items-center justify-center h-40 text-gray-500 gap-2">
                        <ShieldCheck size={32} className="opacity-20" />
                        <span className="text-sm">No significant manipulation traces found.</span>
                    </div>
                )}
            </div>

            <div className="mt-6 pt-6 border-t border-white/5">
                <h5 className="text-xs font-mono text-gray-500 uppercase mb-2">Reasoning Chain</h5>
                <p className="text-xs text-gray-400 font-mono leading-relaxed opacity-80">
                    {result.reasoning}
                </p>
            </div>
          </div>
      </div>

      <div className="flex justify-center pt-8">
        <button 
          onClick={onReset}
          className="group relative px-8 py-3 bg-brand-600 hover:bg-brand-500 text-white rounded-full font-medium transition-all shadow-[0_0_20px_rgba(2,132,199,0.4)] hover:shadow-[0_0_30px_rgba(2,132,199,0.6)] flex items-center gap-2 overflow-hidden"
        >
          <div className="absolute inset-0 bg-gradient-to-r from-transparent via-white/20 to-transparent -translate-x-full group-hover:translate-x-full transition-transform duration-1000"></div>
          <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" /></svg>
          <span className="relative">Analyze New Subject</span>
        </button>
      </div>
    </div>
  );
};

const MetricRow = ({ label, value, icon }: { label: string, value: number, icon: any }) => (
    <div className="flex items-center justify-between p-2 rounded bg-white/5">
        <div className="flex items-center gap-2 text-gray-400 text-xs font-medium uppercase">
            {icon} {label}
        </div>
        <div className="flex items-center gap-2">
            <div className="w-16 h-1.5 bg-gray-700 rounded-full overflow-hidden">
                <div className="h-full bg-brand-500 rounded-full" style={{ width: `${value * 10}%` }}></div>
            </div>
            <span className="font-mono text-xs font-bold text-white w-6 text-right">{value}</span>
        </div>
    </div>
);

export default ResultsDashboard;